export const staticEffects = {
    "11": "desligado",
    "1": "vermelho",
    "2": "verde",
    "3": "azul",
    "4": "branco",
    "5": "verde",
    "6": "rosa",
    "7": "ciano",
    "8": "roxo",
    "9": "amarelo",
    "10": "laranja",
    "12": "flashes",
    "13": "pulso em StandBy",
    "14": "fade em StandBy",
    "15": "fogo",
    "16": "chuva",
    "17": "quente",
    "18": "frio",
    "19": "efeitos aleatorios",
};

export const staticEffectsNames = {
    "11": "gray",
    "1": "red",
    "2": "green",
    "3": "blue",
    "4": "gainsboro",
    "5": "green",
    "6": "pink",
    "7": "cyan",
    "8": "purple",
    "9": "yellow",
    "10": "orange",
    "12": "blink-flashes",
    "13": "blink-pulse-stand-by",
    "14": "blink-fade-stand-by",
    "15": "blink-fire",
    "16": "blink-rain",
    "17": "blink-hot",
    "18": "blink-cold",
    "19": "blink-random",
};

export const dynamicsEffects = {
    "12": "flashes",
    "13": "pulso em StandBy",
    "14": "fade em StandBy",
    "15": "fogo",
    "16": "chuva",
    "17": "quente",
    "18": "frio",
    "19": "efeitos aleatorios",
};